### ISSUE TITLE
[Test Query] - transaction address needs to be turned into link 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#79] opened 2018-03-20 23:01 UTC
![image](https://user-images.githubusercontent.com/15096737/37687220-a70614de-2cd5-11e8-90b7-fd2974bd117f.png)

Instead of the long URL we should create a nice clickable link to etherscan

**Comment by maektwain** [comment] 2018-03-26 18:22
How do I reproduce the above step, because in my case it does not show the url part.

**Comment by cryptomental** [comment] 2018-03-26 19:05
@maektwain 

Could you please confirm that you unlocked MetaMask, ethereum bridge initialized correctly and migration was successful?

**Comment by maektwain** [comment] 2018-03-26 19:32
@cryptomental  Yeah I did as you said.  When on Rinkeby network it says : OraclizeQueryTest has not been deployed to detected network (network/artifact mismatch)

**Comment by cryptomental** [comment] 2018-03-26 20:59
@maektwain this is because OraclizeQueryTest is not deployed to Rinkeby. Please follow the readme to spin up the private test network.

**Comment by maektwain** [comment] 2018-03-26 23:07
Are you talking about orcalize or Dapps

**Comment by cryptomental** [comment] 2018-03-27 06:44
I was referring to the dApp.  Please make sure that you migrated 0.0.20 market-solidity in your network.

**Comment by cryptomental** [comment] 2018-03-29 07:46
Ok I tried this one and what happens is that in message.js JSX in injected as follows to msgBody:

```
const msgBody = (
    <span>
      {content}
      <Icon type="close-circle" onClick={handleDismiss} style={iconStyle} />
    </span>
  );
```

When the hyperlink is injected straight into msgBody, it is correctly parsed and displayed:

```
const msgBody = (
    <span>
      <a href="https://rinkeby.etherscan.io/tx/121212">121212</a>
      {content}
      <Icon type="close-circle" onClick={handleDismiss} style={iconStyle} />
    </span>
  );
```

But when the hyperlink is provided in {content} , and expanded by JSX which is currently the case , it is treated like a raw string
" <a href="https://rinkeby.etherscan.io/tx/121212">121212</a>". and displayed in a raw form.

To solve this ticket, one needs to know how React resolves HTML tags in JSX strings.

@maektwain perhaps this will help you, if not @eswarasai / @perfectmak  / @KennethAshley we need your help.

**Comment by maektwain** [comment] 2018-04-01 11:27
@cryptomental 

```
const message = (network, hash) => {
  let message = 'Transaction has been submitted: ';
  
  switch(network) {
    case 'rinkeby':
      message = message +  message.link(`https://rinkeby.etherscan.io/tx/${hash}`);
      break;
    case 'mainnet':
      message = message + `https://etherscan.io/tx/${hash}`;
      break;
    case 'unknown':
      message = message + `${hash}`;
      break;
    default:
      message = 'Transaction has been submitted';
  }
```

we can use link() method to achieve the desired result.

**Comment by cryptomental** [comment] 2018-04-02 18:19
@maektwain great! please open a pull request with the change if that works correctly.

**Comment by eswarasai** [comment] 2018-04-03 12:11
@maektwain -- Any update on the PR for this? Looking forward to getting this merged.

**Comment by cryptomental** [comment] 2018-04-04 08:33
@maektwain @eswarasai  the proposed solution with message.link does not work. I took time to check this. The behaviour is exactly the same as in my comment above.

![image](https://user-images.githubusercontent.com/20819151/38297009-6a5a8f8c-37f3-11e8-8480-3e85ec90e76b.png)

**Comment by maektwain** [comment] 2018-04-04 09:05
How would you deal with messages containing tags, e.g. links?

For example this can't be rendered by React:

const message = 'Visit <a href="https://github.com">github</a> now!';

A solution is that in use by khan academy. Then I would write something like:

const messages = { visit: 'Visit %(link)s now!', link: 'github' }
<p>
  <$_ link={ <a href="https://github.com">this.getIntlMessage('link')</a> }>
       { this.getIntlMessage('visit') }
  </$_>
</p>

**Comment by pelsasser** [comment] 2018-04-05 23:49
@maektwain - can you let us know status of this? Would like to get some folks from gitcoin involved to move this one along.

**Comment by maektwain** [comment] 2018-04-08 10:28
<img width="510" alt="screen shot 2018-04-08 at 3 56 10 pm" src="https://user-images.githubusercontent.com/8274610/38466360-a189acc2-3b45-11e8-8cd0-a464f0642574.png">

**Closed** 2018-04-23 15:49 UTC
Labels: enhancement, good first issue, help wanted
